# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='email',
        ),
        migrations.AlterField(
            model_name='people',
            name='followed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
    ]
